[versions]
kotlin = "2.4.10"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
springdoc-openapi = "3.0.3"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
springdoc-openapi-starter-webmvc-scalar = { module = "org.springdoc:springdoc-openapi-starter-webmvc-scalar", version.ref = "springdoc-openapi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }